import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const Moderat = localFont({
  src: [
    {
      path: '../public/fonts/Moderat-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Moderat-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Moderat-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-moderat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${Moderat.variable} font-display text-slate-800 dark:text-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
